default_platform(:ios)

platform :ios do
  lane :beta do
    match(type: "appstore", readonly: is_ci)
    build_app(
      scheme: "Runner",
      workspace: "ios/Runner.xcworkspace",
      export_method: "app-store"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  lane :certs do
    match(type: "appstore")
  end
end
